swagger: "2.0"
info:
  version: "0.0.1"
  title: LXD API
# during dev, should point to your local machine
host: 192.168.50.4:9000
# basePath prefixes all resource paths 
basePath: /v1
schemes:
  - http
  - https
#securityDefinitions:
#  apiKey:
#    type: apiKey
#    name: apiKey
#    in: header
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /authenticate:
    x-swagger-router-controller: auth
    post:
      description: Authenticate a user session and return the API key
      operationId: signin
      parameters:
        - name: user
          in: body
          description: User
          required: true
          schema:
            $ref: '#/definitions/UserModel'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AuthResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /serverinfo:
    x-swagger-router-controller: serverinfo
    get:
      description: Returns server information
      # used as the method name of the controller
      operationId: get
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ServerInfoResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /container:
    x-swagger-router-controller: container
    get:
      description: Returns container information
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: name
          in: query
          description: Container name
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContainerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /containers:
    x-swagger-router-controller: containers
    get:
      description: Returns a list of containers
      # used as the method name of the controller
      operationId: get
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ContainersResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserModel:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  ContainerModel: 
    required:
      - name
    properties: 
      name:
        type: string
  AuthResponse:
    required:
      - apiKey
    properties:
      apiKey:
        type: string
  ServerInfoResponse:
    required:
      - serverinfo
    properties:
      serverinfo:
        type: object
  ContainersResponse:
    required:
      - containers
    properties:
      containers:
        type: array
        items:
          $ref: "#/definitions/ContainerModel"
  ContainerResponse:
    required: 
      - container
    properties: 
      container:
        $ref: "#/definitions/ContainerModel"
  ErrorResponse:
    required:
      - error
    properties:
      error:
        type: string
